---
abstract: 'Response Content Body Encoder for JSON, XML, YAML, etc.'
author:
  - 'Yusuke Kawasaki'
build_requires:
  Test::More: 0.71
  Test::Pod: 1.41
configure_requires:
  ExtUtils::MakeMaker: 6.55
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Response-Data
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  HTTP::Status: 6.00
  JSON: 2.00
  Plack: 0.9948
  XML::TreePP: 0.41
  YAML::Any: 0.67
version: 0.01
